<a href="https://colab.research.google.com/github/MilanVarma/Pytorch-Fundamentals/blob/main/PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Introduction to Tensors

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([7,7])

In [ ]:
vector.ndim

1

In [ ]:
#matrix
matrix = torch.tensor([[7,8],
                       [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
#Tensor
tensor = torch.tensor([[[1,2,3],
                        [3,5,6],
                        [6,7,8]],
                       [[8,8,8],
                        [8,8,8],
                        [9,9,9]]])
tensor

tensor([[[1, 2, 3],
         [3, 5, 6],
         [6, 7, 8]],

        [[8, 8, 8],
         [8, 8, 8],
         [9, 9, 9]]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor.shape

torch.Size([2, 3, 3])

In [ ]:
tensor[1,2,1]

tensor(9)

### Random tensors

In [ ]:
#Random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0343, 0.7684, 0.7001, 0.5150],
        [0.4545, 0.5590, 0.4826, 0.7401],
        [0.5653, 0.6841, 0.2065, 0.8680]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
#Random tensor with similar shape of an image
random_image_tensor = torch.rand(size=(3,244,244))
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([3, 244, 244]), 3)

Creating a range of tensors

In [ ]:
torch_range = torch.arange(0,10,2)
torch_range

tensor([0, 2, 4, 6, 8])

In [ ]:
#Creating tensors like
ten_zero = torch.zeros_like(input=torch_range)
ten_zero

tensor([0, 0, 0, 0, 0])

## **Tensor Data Types**

In [ ]:
data_type_tensor = torch.tensor([3.0,6.0,9.0],
                                dtype=None,
                                device=None,
                                requires_grad=False)
data_type_tensor

tensor([3., 6., 9.])

In [ ]:
data_type_tensor.dtype

torch.float32

In [ ]:
data_type_tensor = data_type_tensor.type(torch.half)
data_type_tensor.dtype

torch.float16

In [ ]:
# Getting information from tensors

some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.1512, 0.9128, 0.2939, 0.4663],
        [0.1691, 0.1650, 0.4046, 0.1694],
        [0.1334, 0.8096, 0.1141, 0.7176]])

In [ ]:
some_tensor.dtype

torch.float32

In [ ]:
some_tensor.shape

torch.Size([3, 4])

In [ ]:
some_tensor.device

device(type='cpu')

# Manipulating Tensors
Tensor Operations
Addition
Subtraction
Multiplication
Division
Matrix

In [ ]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [ ]:
torch.mul(tensor,5)

tensor([ 5, 10, 15])

In [ ]:
torch.sub(tensor,5)

tensor([-4, -3, -2])

### Matrix Multiplication

In [ ]:
# Element wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [ ]:
#Matric Multiplication
torch.matmul(tensor, tensor)

tensor(14)

### Tensor Aggregation
Min, max, mean, sum etc

In [ ]:
x = torch.arange(0,100, 5)

In [ ]:
torch.min(x)

tensor(0)

In [ ]:
torch.max(x)

tensor(95)

In [ ]:
torch.mean(x.type(torch.float32))

tensor(47.5000)

In [ ]:
torch.sum(x)

tensor(950)

### Replacing, stacking, squeezing, unsqueezing

In [ ]:
x = torch.arange(1., 13.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [ ]:
#Reshape
x_reshaped = x.reshape(1,12)

In [ ]:
#Stack
torch.stack([x,x,x,x], dim=0)

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [ ]:
x_reshaped.shape

torch.Size([1, 12])

In [ ]:
x_reshaped.squeeze().shape

torch.Size([12])